export const IpcMainToRender = {
  appResume: "appResume",
  runtimeEvent: "runtime:event",
  terminalEvent: "terminal:event",
  agentStructuredOutput: "agent:structuredOutput",
};

export const IpcRenderToMain = {
  showMainWindow: "showMainWindow",
  clearSession: "clearSession",
  minimizeWindow: "minimizeWindow",
  maxmizeWindow: "maxmizeWindow",
  closeWindow: "closeWindow",
  showMessageBox: "showMessageBox",
  setKeyStore: "setKeyStore",
  getKeyStore: "getKeyStore",
  getKeyStoreSync: "getKeyStoreSync",
  showInputContextMenu: "showInputContextMenu",
  getDataPath: "getDataPath",
  runtimeListProfiles: "runtime:listProfiles",
  runtimeStart: "runtime:start",
  runtimeInterrupt: "runtime:interrupt",
  runtimeStop: "runtime:stop",
  runtimeWriteInput: "runtime:writeInput",
  runtimeResize: "runtime:resize",
  runtimeHealthCheck: "runtime:healthCheck",
  terminalStart: "terminal:start",
  terminalInterrupt: "terminal:interrupt",
  terminalStop: "terminal:stop",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalGetWorkspaceDir: "terminal:getWorkspaceDir",
  terminalOpenWorkspace: "terminal:openWorkspace",

  fileSelectFiles: "file:selectFiles",
  fileSelectFolder: "file:selectFolder",
  fileStatNativePath: "file:statNativePath",
  fileOpenPath: "file:openPath",
  fileShowItemInFolder: "file:showItemInFolder",
  fileDownloadToLocal: "file:downloadToLocal",

  agentStartWatch: "agent:startWatch",
  agentStopWatch: "agent:stopWatch",
  opencodeProbeServer: "opencode:probeServer",
  opencodeStartServer: "opencode:startServer",
  opencodeStopServer: "opencode:stopServer",
  opencodeGetBinding: "opencode:getBinding",

  workspaceGetConversationDir: "workspace:getConversationDir",
  workspaceWriteFile: "workspace:writeFile",
  workspaceWriteWorkspaceFile: "workspace:writeWorkspaceFile",
  workspaceCopyWorkspaceFile: "workspace:copyWorkspaceFile",
  workspaceDownloadWorkspaceFile: "workspace:downloadWorkspaceFile",
  workspaceStatFile: "workspace:statFile",
  folderScan: "folder:scan",
  folderDownloadAllResources: "folder:downloadAllResources",
  folderDownloadShare: "folder:downloadShare",
};
