export const IpcMainToRender = {
  appResume: "appResume",
  runtimeEvent: "runtime:event",
  terminalEvent: "terminal:event",
  agentStructuredOutput: "agent:structuredOutput",
  agentSessionEvent: "agent-session:event",
};

export const IpcRenderToMain = {
  showMainWindow: "showMainWindow",
  clearSession: "clearSession",
  minimizeWindow: "minimizeWindow",
  maxmizeWindow: "maxmizeWindow",
  closeWindow: "closeWindow",
  showMessageBox: "showMessageBox",
  setKeyStore: "setKeyStore",
  getKeyStore: "getKeyStore",
  getKeyStoreSync: "getKeyStoreSync",
  appGetConfigSync: "app:getConfigSync",
  appGetConfigPath: "app:getConfigPath",
  showInputContextMenu: "showInputContextMenu",
  getDataPath: "getDataPath",
  runtimeListProfiles: "runtime:listProfiles",
  runtimeStart: "runtime:start",
  runtimeInterrupt: "runtime:interrupt",
  runtimeStop: "runtime:stop",
  runtimeWriteInput: "runtime:writeInput",
  runtimeResize: "runtime:resize",
  runtimeHealthCheck: "runtime:healthCheck",
  terminalStart: "terminal:start",
  terminalInterrupt: "terminal:interrupt",
  terminalStop: "terminal:stop",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalGetWorkspaceDir: "terminal:getWorkspaceDir",
  terminalOpenWorkspace: "terminal:openWorkspace",

  fileSelectFiles: "file:selectFiles",
  fileSelectFolder: "file:selectFolder",
  fileStatNativePath: "file:statNativePath",
  fileOpenPath: "file:openPath",
  fileShowItemInFolder: "file:showItemInFolder",
  fileDownloadToLocal: "file:downloadToLocal",

  agentStartWatch: "agent:startWatch",
  agentStopWatch: "agent:stopWatch",
  opencodeProbeServer: "opencode:probeServer",
  opencodeStartServer: "opencode:startServer",
  opencodeStopServer: "opencode:stopServer",
  opencodeGetBinding: "opencode:getBinding",

  agentSessionList: "agent-session:list",
  agentSessionCreate: "agent-session:create",
  agentSessionUpdate: "agent-session:update",
  agentSessionArchive: "agent-session:archive",
  agentSessionSelect: "agent-session:select",
  agentSessionSend: "agent-session:send",
  agentSessionAbort: "agent-session:abort",
  agentSessionRecover: "agent-session:recover",
  agentSessionReplyPermission: "agent-session:replyPermission",
  agentSessionReplyQuestion: "agent-session:replyQuestion",
  agentSessionSetAutoApprove: "agent-session:setAutoApprove",
  agentSessionGetAutoApprove: "agent-session:getAutoApprove",
  agentSessionMarkRead: "agent-session:markRead",
  agentSessionSetViewport: "agent-session:setViewport",
  agentSessionSetPanelState: "agent-session:setPanelState",
  agentSessionSetBotPolicy: "agent-session:setBotPolicy",
  agentSessionSetBotCheckpoint: "agent-session:setBotCheckpoint",
  agentSessionAddBotRequest: "agent-session:addBotRequest",
  agentSessionEnsureBotSession: "agent-session:ensureBotSession",
  agentSessionIgnoreBotRequest: "agent-session:ignoreBotRequest",
  agentSessionRunBotRequest: "agent-session:runBotRequest",
  agentSessionWriteFiles: "agent-session:writeFiles",
  agentSessionHistoryResponse: "agent-session:historyResponse",
  agentSessionOpenTerminal: "agent-session:openTerminal",

  workspaceGetConversationDir: "workspace:getConversationDir",
  workspaceWriteFile: "workspace:writeFile",
  workspaceWriteWorkspaceFile: "workspace:writeWorkspaceFile",
  workspaceCopyWorkspaceFile: "workspace:copyWorkspaceFile",
  workspaceDownloadWorkspaceFile: "workspace:downloadWorkspaceFile",
  workspaceStatFile: "workspace:statFile",
  folderScan: "folder:scan",
  folderDownloadAllResources: "folder:downloadAllResources",
  folderDownloadShare: "folder:downloadShare",
};
